---
name: linting

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read # Required to check out the module sources.

concurrency:
  group: linting-${{ github.event.pull_request.head.repo.full_name }}/${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  docs:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: docs
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: check docs
        uses: $/.github/actions/docs-check

  terraform:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: terraform
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: lint terraform
        uses: $/.github/actions/linting
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  avmfix:
    if: github.event.repository.name != 'terraform-azurerm-avm-template'
    name: avmfix
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: avmfix
        uses: $/.github/actions/avmfix

  lintcomplete:
    name: lint complete
    needs: [docs, terraform, avmfix]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All linting checks passed"
